### ISSUE TITLE
Storyboard Support?

### ISSUE THREAD

**Issue by codeOfRobin** [aleph7/PlotKit#10]
Can't seem to get it to work with storyboards.

Always getting Unknown class PlotView in Interface Builder file at path/.....

**Comment by alejandro-isaza** [comment]
How are you importing the PlotKit framework? CocoaPods? Make sure that the module part is set properly: 
<img width="261" alt="screen shot 2016-05-12 at 10 45 01 am" src="https://cloud.githubusercontent.com/assets/167236/15224508/a5f79d96-182e-11e6-8a1c-00b197042470.png">

**Comment by codeOfRobin** [comment]
I was using Carthage. And although it didn't autofill 'Plotkit', still worked. Thanks! You might wanna add that to the README. Hold on, I'll make a PR.
